# Generated by Django 3.1.7 on 2021-04-11 12:37

import court.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Judge', 'Judge'), ('Lawyer', 'Lawyer')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('court_type', models.CharField(choices=[('SUP', 'Supreme Court'), ('HIG', 'High Court'), ('DST', 'District Court'), ('SES', 'Session Court')], max_length=20)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('license_no', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_applicant', models.CharField(max_length=400)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('case_type', models.CharField(choices=[('CIV', 'Civil'), ('CRI', 'Criminal')], max_length=3)),
                ('court_type', models.CharField(choices=[('SUP', 'Supreme Court'), ('HIG', 'High Court'), ('DST', 'District Court'), ('SES', 'Session Court')], max_length=3)),
                ('subject', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to=court.models.user_directory_path)),
                ('cnr', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('fileNo', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_respondent', models.CharField(max_length=400, null=True)),
                ('lawyer_of_respondent', models.CharField(max_length=400, null=True)),
                ('address_of_respondent', models.CharField(max_length=500, null=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_user', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_user', to='court.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('license_no', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=500)),
                ('court_type', multiselectfield.db.fields.MultiSelectField(choices=[('SUP', 'Supreme Court'), ('HIG', 'High Court'), ('DST', 'District Court'), ('SES', 'Session Court')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
