# Generated by Django 3.1.7 on 2021-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='file_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
