# Generated by Django 3.1.7 on 2021-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_case_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
