# Generated by Django 3.1.7 on 2021-04-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_auto_20210412_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='phone_number',
        ),
    ]
