# Generated by Django 3.1.7 on 2021-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_remove_case_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
