# Generated by Django 3.1.7 on 2021-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0007_auto_20210413_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verdict',
            field=models.CharField(blank=True, choices=[('Guilty', 'Guilty'), ('Not-Guilty', 'Not-Guilty')], max_length=10, null=True),
        ),
    ]
