# Generated by Django 3.1.7 on 2021-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0010_auto_20210421_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='hr',
            field=models.BooleanField(default=False),
        ),
    ]
