# Generated by Django 3.1.7 on 2021-04-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0011_case_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='file',
            new_name='docs',
        ),
    ]
