# Generated by Django 3.1.7 on 2021-04-23 21:22

import court.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0014_auto_20210424_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='docs',
        ),
        migrations.AddField(
            model_name='case',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=court.models.user_directory_path),
        ),
    ]
